### ISSUE TITLE
can't convert value useMuraDefault to a datetime value

### ISSUE THREAD

**Issue by ghost** [nolanerck/MuraGoogleNewsSitemaps#1]
Hello, I just installed on a new site launch and am having an issue when I click on the settings tab. I get the following error.

can't convert value useMuraDefault to a datetime value

I am running on coldfusion 10 and Mura 7.0.6919.
Any help would be appreciated. Thanks.

**Comment by nolanerck** [comment]
I ran into that once during development but it vanished; I've got an idea what might be happening, I'll take a look.

Just for reference, what database are you using?

**Comment by ghost** [comment]
Thank you you for your interest, MS SQL 2016 is the database.

2017-02-22 20:58 GMT+01:00 Nolan Erck <notifications@github.com>:

**Comment by ghost** [comment]
Now it works!
I have not associated the site domain in the configuration.
Sorry for disturbing.
Alfredo

2017-02-22 20:58 GMT+01:00 Nolan Erck <notifications@github.com>:

**Comment by nolanerck** [comment]
Thanks for posting the fix, much appreciated. Glad you're getting use out of the plugin. :)
